/// Die bekanntesten Pilzarten (deutsche Namen) für die Vorschlagsliste.
/// Bewusst eine einfache Namensliste — eigene Arten des Users entstehen
/// automatisch aus seinen Funden (Freitext bleibt immer möglich).
const kBekannteArten = <String>[
  // Beliebte Speisepilze
  'Steinpilz',
  'Pfifferling',
  'Maronenröhrling',
  'Birkenpilz',
  'Rotkappe',
  'Butterpilz',
  'Goldröhrling',
  'Sandröhrling',
  'Ziegenlippe',
  'Flockenstieliger Hexenröhrling',
  'Netzstieliger Hexenröhrling',
  'Sommersteinpilz',
  'Kiefernsteinpilz',
  'Parasol',
  'Safranschirmling',
  'Wiesenchampignon',
  'Stadtchampignon',
  'Anischampignon',
  'Krause Glucke',
  'Herbsttrompete',
  'Trompetenpfifferling',
  'Semmelstoppelpilz',
  'Austernseitling',
  'Stockschwämmchen',
  'Hallimasch',
  'Violetter Rötelritterling',
  'Nebelkappe',
  'Mönchskopf',
  'Grünling',
  'Reifpilz',
  'Perlpilz',
  'Speisemorchel',
  'Spitzmorchel',
  'Frühjahrslorchel',
  'Schopftintling',
  'Riesenbovist',
  'Flaschenstäubling',
  'Judasohr',
  'Samtfußrübling',
  'Fichtenreizker',
  'Edelreizker',
  'Lachsreizker',
  'Mohrenkopfmilchling',
  'Brätling',
  'Frauentäubling',
  'Speisetäubling',
  'Ledertäubling',
  'Fichtensteinpilz',
  'Schwefelporling',
  'Leberpilz',
  'Igelstachelbart',
  'Sparriger Schüppling',
  'Waldchampignon',
  'Riesenschirmling',
  'Dunkler Hallimasch',
  'Winterrübling',
  'Espenrotkappe',
  'Birkenrotkappe',
  'Gemeiner Steinpilz',
  'Bronzeröhrling',
  // Bekannte Gift- und Verwechslungspilze (fürs Dokumentieren)
  'Fliegenpilz',
  'Grüner Knollenblätterpilz',
  'Kegelhütiger Knollenblätterpilz',
  'Pantherpilz',
  'Karbolchampignon',
  'Gifthäubling',
  'Grünblättriger Schwefelkopf',
  'Kahler Krempling',
  'Satansröhrling',
  'Gallenröhrling',
  'Spitzgebuckelter Raukopf',
  'Orangefuchsiger Raukopf',
  'Frühjahrsknollenblätterpilz',
  'Riesenrötling',
  'Tigerritterling',
  'Ziegelroter Risspilz',
  'Fuchsiger Rötelritterling',
  'Falscher Pfifferling',
];
